USE AdventureWorksLT2022
GO
--CREATE ROLE Sales;  

CREATE LOGIN Barry WITH PASSWORD = 'BigData257!'
CREATE USER Barry FOR LOGIN Barry;
ALTER ROLE Sales ADD MEMBER Barry;  
ALTER ROLE Sales DROP MEMBER Barry;